site_name: Mahmoodur Rahman
site_url: https://mahm00d27.github.io

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand

  palette:
    - scheme: default
      primary: blue
      accent: teal

nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Projects: projects.md
  - Publications: publications.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search
``
