site_name: Mahmoodur Rahman
site_url: https://mahm00d27.github.io


theme:
  name: material

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.sections
    - content.code.copy

  palette:

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Projects: projects.md
  - Publications: publications.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

plugins:
  - search

extra_css:
  - styles.cs

