site_name: Mahmoodur Rahman

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top

  palette:
    - scheme: default
      primary: blue
      accent: teal

nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Projects: projects.md
  - Publications: publications.md
